// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sotashi.Core.Infastructure.DbContexts;

namespace Sotashi.Core.Infastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sotashi.Core.Infastructure.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea317"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(3447),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(3450),
                            Name = "Dave"
                        },
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea318"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(3588),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(3589),
                            Name = "George"
                        },
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea319"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(3610),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(3611),
                            Name = "Fiona"
                        },
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea320"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(3628),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(3630),
                            Name = "Rory"
                        },
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea321"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(3646),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(3647),
                            Name = "Olivia"
                        });
                });

            modelBuilder.Entity("Sotashi.Core.Infastructure.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea314"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 332, DateTimeKind.Utc).AddTicks(1643),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 332, DateTimeKind.Utc).AddTicks(2126),
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea315"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(2673),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(2678),
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea316"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(2758),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(2760),
                            Name = "Keyboard"
                        });
                });

            modelBuilder.Entity("Sotashi.Core.Infastructure.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea322"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(4937),
                            CustomerId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea317"),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(4940),
                            Price = 900.0,
                            ProductId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea314")
                        },
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea323"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(5155),
                            CustomerId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea318"),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(5156),
                            Price = 35.0,
                            ProductId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea315")
                        },
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea324"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(5176),
                            CustomerId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea319"),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(5178),
                            Price = 5.0,
                            ProductId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea316")
                        },
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea325"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(5195),
                            CustomerId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea320"),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(5197),
                            Price = 3.0,
                            ProductId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea316")
                        },
                        new
                        {
                            Id = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea326"),
                            CreatedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            CreatedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(5213),
                            CustomerId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea321"),
                            LastModifiedBy = new Guid("825f1646-9fa2-41c2-97c2-1bcc3912e890"),
                            LastModifiedOn = new DateTime(2021, 12, 15, 9, 15, 19, 333, DateTimeKind.Utc).AddTicks(5214),
                            Price = 600.0,
                            ProductId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea314")
                        });
                });

            modelBuilder.Entity("Sotashi.Core.Infastructure.Entities.Sale", b =>
                {
                    b.HasOne("Sotashi.Core.Infastructure.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sotashi.Core.Infastructure.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
